AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description:
Resources:
  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: './dist/api.zip'
      Runtime: nodejs8.10
      Events:
        CollectionApi:
          Type: Api
          Properties:
            Path: /students
            Method: any
        ItemApi:
          Type: Api
          Properties:
            Path: /students/{id}
            Method: any
      Environment:
        Variables:
          DBURL: 'mongodb+srv://mongo_user:wAAbUC36OzKcm0hN@cluster0-knpmq.mongodb.net/boilerplate'