AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: For Student lambda
Resources:
  StudentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://kedari-test-lambda-deploy/8a0ad71e9173ba95df8811c9e5b96eb1
      Runtime: nodejs8.10
      Events:
        CollectionApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestAPI
            Method: any
            Path: /students
        ItemApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestAPI
            Method: any
            Path: /students/{id}
      Environment:
        Variables:
          DBURL: mongodb+srv://mongo_user:wAAbUC36OzKcm0hN@cluster0-knpmq.mongodb.net/boilerplate
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-apiKey
      Description: StudentApiKey
      Enabled: true
      GenerateDistinctId: false
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
      - ApiId:
          Ref: StudentAPI
      UsagePlanName:
        Fn::Sub: ${AWS::StackName}-apiUsagePlan
  RestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: StudentAPI
        basePath: /
        schemes:
        - https
        paths:
          /students:
            get:
              response: {}
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StudentFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
